/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#000000",
        "tertiary-fixed": "#e2e2e2",
        "surface-container": "#eeeeee",
        "tertiary-fixed-dim": "#c6c6c6",
        "secondary-fixed-dim": "#c8c6c4",
        "outline": "#7e7576",
        "on-surface": "#1b1b1b",
        "error": "#ba1a1a",
        "on-surface-variant": "#4c4546",
        "burgundy": "#4A0E0E",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary-fixed": "#1b1c1b",
        "on-error-container": "#93000a",
        "silver-noir": "#A8A9AD",
        "on-tertiary-fixed": "#1b1b1b",
        "surface-dim": "#dadada",
        "outline-variant": "#cfc4c5",
        "on-tertiary": "#ffffff",
        "surface": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "primary-fixed": "#e2e2e2",
        "on-primary": "#ffffff",
        "bone": "#FFFFFF",
        "inverse-surface": "#303030",
        "on-primary-fixed": "#1b1b1b",
        "surface-container-highest": "#e2e2e2",
        "surface-tint": "#5e5e5e",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "espresso": "#2D2926",
        "tertiary-container": "#1b1b1b",
        "on-error": "#ffffff",
        "surface-variant": "#e2e2e2",
        "secondary": "#5e5e5d",
        "on-tertiary-container": "#848484",
        "surface-container-low": "#f3f3f3",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        "on-secondary-fixed-variant": "#474746",
        "secondary-fixed": "#e4e2e0",
        "on-background": "#1b1b1b",
        "on-secondary-container": "#636361",
        "on-primary-fixed-variant": "#474747",
        "background": "#f9f9f9",
        "primary": "#000000",
        "surface-bright": "#f9f9f9",
        "primary-fixed-dim": "#c6c6c6",
        "secondary-container": "#e1dfdd",
        "on-tertiary-fixed-variant": "#474747",
        "primary-container": "#1b1b1b",
        "butter": "#F2E8CF"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "unit": "4px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "section-gap": "120px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};