export const bagsData = [
  {
    id: "butter-ring-handle-bag",
    name: "Verafied New York Café Mini Bag",
    price: 248.00,
    category: "shoulder",
    color: "Maroon",
    colorHex: "#610909ff",
    material: "Leather",
    tag: "New",
    primaryImage: "/sova-images/1.2.png",
    modelImages: ["/sova-images/1.1.png"]
  },
  {
    id: "cream-ring-handle-bag",
    name: "Cream Ring Handle Bag",
    price: 248.00,
    category: "shoulder",
    color: "Cream",
    colorHex: "#e8ddd0",
    material: "Leather",
    tag: "New",
    primaryImage: "/sova-images/2.1.png",
    modelImages: ["/sova-images/2.2.png"]
  },
  {
    id: "gold-chocolate-hobo-bag",
    name: "Gold Chocolate Hobo Bag",
    price: 268.00,
    category: "hobo",
    color: "Chocolate",
    colorHex: "#3d2314",
    material: "Leather",
    tag: null,
    primaryImage: "/sova-images/3.2.png",
    modelImages: ["/sova-images/3.1.png"]
  },
  {
    id: "gold-espresso-suede-hobo",
    name: "Gold Espresso Suede Hobo",
    price: 278.00,
    category: "hobo",
    color: "Espresso",
    colorHex: "#4a3c31",
    material: "Suede",
    tag: "Limited",
    primaryImage: "/sova-images/4.1.png",
    modelImages: ["/sova-images/4.2.png"]
  },
  {
    id: "mini-silver-bag",
    name: "Mini Silver Bag",
    price: 198.00,
    category: "shoulder",
    color: "Silver",
    colorHex: "#c0c0c0",
    material: "Leather",
    tag: "Party Edit",
    primaryImage: "/sova-images/5.1.png",
    modelImages: ["/sova-images/5.2.png"]
  },
  {
    id: "cream-poise-shoulder-bag",
    name: "Cream Poise Shoulder Bag",
    price: 248.00,
    category: "shoulder",
    color: "Cream",
    colorHex: "#e8ddd0",
    material: "Leather",
    tag: null,
    primaryImage: "/sova-images/6.1.png",
    modelImages: ["/sova-images/6.2.png"]
  },
  {
    id: "dark-cherry-shoulder-bag",
    name: "Dark Cherry Shoulder Bag",
    price: 298.00,
    category: "shoulder",
    color: "Cherry",
    colorHex: "#4a0e0e",
    material: "Leather",
    tag: "Restocked",
    primaryImage: "/sova-images/7.1.png",
    modelImages: ["/sova-images/7.2.png"]
  },
  {
    id: "gold-suede-hobo-bag",
    name: "Gold Suede Hobo Bag",
    price: 278.00,
    category: "hobo",
    color: "Suede",
    colorHex: "#a88a64",
    material: "Suede",
    tag: "Trending",
    primaryImage: "/sova-images/8.1.png",
    modelImages: ["/sova-images/8.2.png"]
  },
  {
    id: "gold-chocolate-suede-hobo",
    name: "Gold Chocolate Suede Hobo",
    price: 268.00,
    category: "hobo",
    color: "Chocolate",
    colorHex: "#3d2314",
    material: "Suede",
    tag: null,
    primaryImage: "/sova-images/9.1.png",
    modelImages: ["/sova-images/9.2.png"]
  },
  {
    id: "ivory-poise-shoulder-bag",
    name: "Ivory Poise Shoulder Bag",
    price: 318.00,
    category: "shoulder",
    color: "Ivory",
    colorHex: "#fbfaf7",
    material: "Leather",
    tag: "Exclusive",
    primaryImage: "/sova-images/10.1.png",
    modelImages: ["/sova-images/10.2.png"]
  },
  {
    id: "espresso-suede-book-tote-33",
    name: "Espresso Suede Book Tote 33",
    price: 348.00,
    category: "tote",
    color: "Espresso",
    colorHex: "#4a3c31",
    material: "Suede",
    tag: "Classic",
    primaryImage: "/sova-images/11.1.png",
    modelImages: [
      "/sova-images/11.2.png",
      "/sova-images/11.3.png"
    ]
  },
  {
    id: "espresso-suede-book-tote-25",
    name: "Espresso Suede Book Tote 25",
    price: 298.00,
    category: "tote",
    color: "Espresso",
    colorHex: "#4a3c31",
    material: "Suede",
    tag: "Hot",
    primaryImage: "/sova-images/12.1.png",
    modelImages: ["/sova-images/12.2.png"]
  },
  {
    id: "zebra-shoulder-bag",
    name: "Zebra Shoulder Bag",
    price: 385.00,
    category: "shoulder",
    color: "Zebra",
    colorHex: "#eaeaea",
    material: "Leather",
    tag: null,
    primaryImage: "/sova-images/13.1.png",
    modelImages: ["/sova-images/13.2.png"]
  },
  {
    id: "black-belted-leather-tote",
    name: "Black Belted Leather Tote",
    price: 328.00,
    category: "tote",
    color: "Black",
    colorHex: "#171514",
    material: "Leather",
    tag: "Best Seller",
    primaryImage: "/sova-images/14.1.png",
    modelImages: ["/sova-images/14.2.png"]
  },
  {
    id: "studded-hobo-bag",
    name: "Studded Hobo Bag",
    price: 298.00,
    category: "hobo",
    color: "Black",
    colorHex: "#171514",
    material: "Leather",
    tag: "Trending",
    primaryImage: "/sova-images/16.1.png",
    modelImages: ["/sova-images/16.2.png"]
  },
  {
    id: "minimalist-suede-shoulder-bag",
    name: "Minimalist Suede Shoulder Bag",
    price: 258.00,
    category: "shoulder",
    color: "Brown",
    colorHex: "#8b5a2b",
    material: "Suede",
    tag: null,
    primaryImage: "/sova-images/17.1.png",
    modelImages: ["/sova-images/17.2.png"]
  },
  {
    id: "chocolate-suede-hobo",
    name: "Chocolate Suede Hobo",
    price: 278.00,
    category: "hobo",
    color: "Espresso",
    colorHex: "#4a3c31",
    material: "Suede",
    tag: null,
    primaryImage: "/sova-images/18.1.png",
    modelImages: ["/sova-images/18.2.png"]
  }
];
